name: Update View Count

on:
  schedule:
    - cron: '0 * * * *'  # every hour (or use `push`, `page_build`, etc.)
  workflow_dispatch:      # allow manual run

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update view count
      run: |
        count=$(jq '.count' views.json)
        new_count=$((count + 1))
        echo "{\"count\": $new_count}" > views.json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add views.json
        git commit -m "Update view count"
        git push
